function(CheckLibrary)
    if (APPLE)
        include_directories(/usr/local/opt/gmp/include /usr/local/opt/fftw/include)
        link_directories(/usr/local/opt/gmp/lib /usr/local/opt/fftw/lib)
        add_definitions(-DHAVE_READPASSPHRASE=1)

        find_library(HAVE_CRYPTOPP cryptopp)
        if(HAVE_CRYPTOPP)
            add_definitions(-DHAVE_CRYPTOPP=1)
            include_directories(/usr/local/opt/cryptopp/include)
            link_directories(/usr/local/opt/cryptopp/lib)
        else()
            message(WARNING "install cryptopp by homebrew is better")
        endif()

    elseif(UNIX)
        include_directories(/usr/include)
        link_directories(/usr/lib)

        find_library(HAVE_BSDREADPASSPHRASE bsd)
        if (HAVE_BSDREADPASSPHRASE)
            add_definitions(-DHAVE_BSDREADPASSPHRASE=1)
        else()
            message(FATAL_ERROR "libbsd missing, you can install libbsd-dev package!")
        endif()

        find_library(HAVE_CRYPTOPP crypto++)
        if(HAVE_CRYPTOPP)
            add_definitions(-DHAVE_CRYPTOPP=1 -DCRYPTOPP_DIR_PLUS=1)
        else()
            message(WARNING "use crypto++ is better")
        endif()

    endif (APPLE)
endfunction()

function(LinTargetLibrary Target)
    target_link_libraries(${Target} fftw3 gmp)

    if (APPLE)
    elseif(UNIX)
        if (HAVE_BSDREADPASSPHRASE)
            target_link_libraries(${Target} bsd)
        endif()
    endif (APPLE)

    if (HAVE_CRYPTOPP)
        if(CRYPTOPP_DIR_PLUS)
            target_link_libraries(${Target} crypto++)
        else()
            target_link_libraries(${Target} cryptopp)
        endif()
    endif ()
endfunction()
